In [1]:
import numpy as np

In [2]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [3]:
x+y

array([[  6.,   8.],
       [ 10.,  12.]])

In [4]:
np.add(x,y)

array([[  6.,   8.],
       [ 10.,  12.]])

In [5]:
x-y

array([[-4., -4.],
       [-4., -4.]])

In [6]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])